name: helptechmobileapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  path: ^1.9.0
  permission_handler: ^10.2.0
  http_parser: 4.0.0
  mime: ^1.0.0
  firebase_core: 3.6.0
  cloud_firestore: ^5.4.4
  camera: ^0.10.5
  image_picker: ^0.8.5+3
  file_picker: ^6.0.0
  firebase_storage: 12.3.3
  path_provider: ^2.1.5
  salomon_bottom_bar: ^3.3.1
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  flutter_secure_storage: ^8.1.0
  jwt_decoder: ^2.0.1
  fl_chart: ^0.69.0
  intl: ^0.17.0
  web_socket_channel: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.10.0

flutter:

  uses-material-design: true

  assets:
    - assets/IAM/
    - assets/IAM/home_logo.PNG
    - assets/IAM/home_wallpaper.PNG

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.ico"